###Sign up User
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "user_name":"Esther John",
    "email":"test123@gmail.com",
    "password":"helloworld"
}

###Sign in User
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "user_name":"Esther John",
    "email":"test123@gmail.com",
    "password":"helloworld"
}

####GET USER PROFILE
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiRXN0aGVyIEpvaG4iLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzM1NTU1Mjc1LCJleHAiOjE3MzU1NzMyNzV9.rHI4NpyZDXtuQdFm1CvatzhJVsSie2dtrnEq6_j9KTI